name: JVM Ergonomics Checker

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        jdkversion: [ '11', '17' ]
        image: ['azul/zulu-openjdk', 'mcr.microsoft.com/openjdk/jdk', 'eclipse-temurin', 'openjdk', 'bellsoft/liberica-openjdk-debian']

    steps:
    - uses: actions/checkout@v3
    - name: Run docker and get SerialGC status (must be true)
      run: ./validate.sh ${{ matrix.image }} ${{ matrix.jdkversion }}
      shell: bash
