name: JVM Ergo RAMPercentage

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build_lts:
    name: RAMPercentage JDK 11/17
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        jdkversion: [ '11', '17' ]
        image: ['azul/zulu-openjdk', 'mcr.microsoft.com/openjdk/jdk', 'eclipse-temurin', 'openjdk', 'bellsoft/liberica-openjdk-debian']
    steps:
    - uses: actions/checkout@v3
    - name: Run docker
      run: bash validate-rampercentage.sh ${{ matrix.image }} ${{ matrix.jdkversion }}
      shell: bash

  build_jdk18:
    name: RAMPercentage JDK 18
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        jdkversion: [ '18' ]
        image: ['eclipse-temurin', 'openjdk', 'bellsoft/liberica-openjdk-debian']
    steps:
    - uses: actions/checkout@v3
    - name: Run docker
      run: bash validate-rampercentage.sh ${{ matrix.image }} ${{ matrix.jdkversion }}
      shell: bash
